### ISSUE TITLE
Bot not receiving messages

### ISSUE THREAD

**Issue by 0x2142** [fbradyirl/webex_bot#12]
* Webex Bot version: latest
* Python version: 3.8
* Operating System: Ubuntu 20 in Windows WSL

### Description

Hi there! I am trying to get a bot up and running with a non-cisco webex account - but it seems the bot is never receiving messages. 

I have previously used this module to create a bot, but it was all using my cisco.com webex account - and I never hit any issues. However, I am trying to create a bot using a personal email/webex account & it doesn't seem to be working.

### What I Did

1. Created new webex bot API token on the Webex Developer site, using my personal email/webex account
2. `pip install webex_bot`
3. Use basic code snippet below to test
4. Send message from @cisco.com account - Bot receives message & responds with help card
5. Send message from non-cisco.com account - Bot never receives message

I also tried enabling debug logging on the bot, but I am never seeing a message come in.

Additionally, if I create a group room with my personal & cisco.com accounts in it - The bot will respond then to a direct @ message from my personal email. However, in a direct 1:1 space it seems the message never makes it to the bot.

```
from webex_bot.webex_bot import WebexBot
bot = WebexBot(api_token)
bot.run()
```

**Comment by 0x2142** [comment]
This seems to be a stange backend issue... If I use the Webex websocket test/demo [page](https://webex.github.io/websocket-demo-page/) - I also never see the messages from my personal email/domain. 

I signed up for another free developer account with a different personal email, and everything works fine.

**Comment by sdargoeuves** [comment]
This is weird, I've got the same issue, I have also tried to use the test/demo [page](https://webex.github.io/websocket-demo-page/) where I can login, but nothing else happens. 
I tried to create a new account, and I've got the same result... Not sure if anyone else has had this problem, any idea what to do to fix this?

**Comment by Viadd** [comment]
I also have this issue, however, even though I created several accounts I still have the problem, if there is another possible solution, I would be grateful if you could tell me about it.
