### ISSUE TITLE
default help card is annoying

### ISSUE THREAD

**Issue by rodhpadilla** [fbradyirl/webex_bot#25]
* Webex Bot version: 0.2.22
* Python version:  3.8.9
* Operating System: macOS

### Description

Any option/recommendation to stop sending the default help card (next image) everytime the user type `help` insted of the one I defined?
![image](https://user-images.githubusercontent.com/47065455/162960945-3743d32b-54ea-4cfa-9f0c-4d3d724cc9f6.png)

### What I Did

```
# action.py
class myAction(Command):
    def __init__(self):
        super().__init__(
            command_keyword="help",
            help_message="My Custom Help",
            card=START_CARD,
        )

# bot.py
bot.help_command = myAction()
help = myAction()
bot.add_command(help)
```

**Comment by gconklin** [comment]
Try this, after you instantiate the bot and the help message:

```
    bot.commands.remove(bot.help_command)
    bot.commands.add(my_help_command)
    bot.help_command = my_help_command
```

**Comment by rodhpadilla** [comment]
> Try this, after you instantiate the bot and the help message:

thanks for the quick feedback @gconklin !   Nice to know that there is a `remove` mothod for this cases.  
Now the default help command it is the one I created
