### ISSUE TITLE
Websocket connection through Proxy Server

### ISSUE THREAD

**Issue by Sly-Turtle** [fbradyirl/webex_bot#35]
* Webex Bot version: 0.3.3
* Python version:  3.9
* Operating System: Windows

Is there an existing way to configure the webex_bot to access webexapis.com through a proxy server? The webexteamssdk module has this functionality but I have not seen anything similar in webex_bot:

 proxy = {'https': 'http://<proxy_ip>:<proxy_port>'}
 api = WebexTeamsAPI(access_token=WEBEX_TEAMS_ACCESS_TOKEN,proxies=proxy)

```
import os
import Token

from webex_bot.webex_bot import WebexBot

webex_token = Token.BOT_WEBEX_TEAMS_ACCESS_TOKEN


bot=WebexBot(webex_token,approved_domains=['domainhere.com'])
bot.run()
```

Without a proxy connection, I get the following error when I execute bot.run().
 
"ConnectionError: HTTPSConnectionPool(host='webexapis.com', port=443): Max retries exceeded with url: /v1/people/me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002570BB6FB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"

**Comment by gconklin** [comment]
I believe this is not possible currently due to webex_bot using the "[websockets](https://websockets.readthedocs.io/en/stable/index.html)" library which does not support a proxy.

https://websockets.readthedocs.io/en/stable/reference/limitations.html?highlight=proxy
https://github.com/aaugustin/websockets/issues/364

**Comment by fbradyirl** [comment]
Correct. If you have a proxy, I think websockets is not the way you want to go.

**Comment by ifreedom** [comment]
@Sly-Turtle you can use `websocket-client` library instead. To use `websocket-client` with `asyncio`, you can look at [wsapi.py](https://github.com/ifreedom/python-ftx/blob/master/ftx/wsapi.py) as a reference.
