### ISSUE TITLE
warning 'open to everyone' still there when defining approved_domains

### ISSUE THREAD

**Issue by jseynaev-cisco** [fbradyirl/webex_bot#7]
* Webex Bot version: latest pip
* Python version: 3.8
* Operating System: windows/docker

### Description

Starting the bot, limited to my domain, still displays the warning

### What I Did
```
bot = WebexBot(
    teams_bot_token=os.getenv("WEBEX_TEAMS_ACCESS_TOKEN", BEARER_TOKEN),
    approved_domains=['mydomain.com'])
```

### Fix
problem is with line 
```
if len(self.approved_users) == 0 and len(self.approved_users) == 0:
```
pretty sure it should not be 'users' twice ;-)

**Comment by fbradyirl** [comment]
Thanks for highlighting!
