### ISSUE TITLE
removeprefix() is 3.9 only

### ISSUE THREAD

**Issue by jseynaev-cisco** [fbradyirl/webex_bot#8]
* Webex Bot version: lastest pip
* Python version: 3.8
* Operating System: windows/docker

### Description

Just running the bot

### What I Did
After receiving a message from the socket
```
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=AttributeError("'str' object has no attribute 'removeprefix'")>

```

### fix / workaround
removeprefix is only introduced in 3.9, so might be better to replace by something like this 
(bottom of the webex_bot.py file)
```
if message.startswith(command):
    return message[len(command):]
return message
```

**Comment by fbradyirl** [comment]
Fixed in #10
